# Generated by Django 4.2.30 on 2026-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_branches',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
